class CpfNaoEncontradoException(Exception):
    def __init__(self):
        super().__init__("O cpf n√£o foi encontrado.")
